trainees/hello_003.txt
=> 003 pull request

trainees/hello_5.txt
I think we should add a second "!"
=> My first pr

trainees/hello_007.txt
This is james bond's secret password
=> James Bond

trainees/hello_004.txt
=> First pr commit

trainees/hello_006.txt
Please review the hello_006.txt file from user 006.
=> This is a new file.

trainees/hello_000.txt
=> My first pull request

trainees/hello_013.txt
Well, this okay, but I misspelled hello.
=> jesse's hello

trainees/hello_021.txt
=> hello world -- gdr

trainees/hello_025.txt
=> Hello there.

trainees/hello_041.txt
Class exercise 6.3 - Glenn fixed his first PR and is submitting a pull request
=> fixed my first pr

trainees/hello_036.txt
Amazing new features every user wants
=> added hello file 036

trainees/hello_033.txt
=> Putting in request for file 033

trainees/hello_038.txt
Attending the git training session means I am learning and growing!
=> Another hello world file

trainees/hello_030.txt
Adding the text document hello_030.txt
=> adding hello_030.txt

trainees/hello_037.txt
Because 037 is the BEST Hello World!
=> added 037 file

trainees/hello_028.txt, trainees/hello_040.txt
=> SVP PR#040

trainees/hello_038.txt
Rebasing is tricky but an essential skill I must master!
=> A bigger view of things

trainees/hello_000.txt
Attempt to change hello_000.txt
Add third line to hello_029.txt
=> Change by RAShaw-sci

trainees/hello_037.txt
=> modified hello_037.txt

trainees/hello_045.txt
=> added hello

trainees/hello_042.txt
=> added info about susana

trainees/hello_043.txt
=> Crystal's new PR

trainees/hello_050.txt
=> start notes on hello_050

trainees/hello_046.txt
=> Tony Sohn's Hello World

trainees/hello_049.txt
=> added new user

trainees/hello_053.txt
=> my new file

trainees/hello_044.txt
requesting to merge my hello world file with STScI's master branch
=> initial commit of hello world file

trainees/hello_047.txt
=> testing rebase

trainees/hello_043.txt
=> New changes

trainees/hello_058.txt
My first pull request in training.
=> Creating by first pr in trainees

trainees/hello_060.txt
my pull request for number 60.
=> fork example

trainees/hello_062.txt
=> 062 says hello

trainees/hello_065.txt
Pull request for the addition of my Hello World file.
=> Added hello_065.txt

trainees/hello_069.txt
=> my hello (from mswam)

trainees/hello_065.txt
=> Edited grbrady's hello file

trainees/hello_069.txt
=> extra hello add

trainees/hello_078.txt
=> First push from student 78

trainees/hello_076.txt
=> Adding DPJ

trainees/hello_084.txt
=> extra extra

trainees/hello_094.txt
As part of GitHub training, I've created a text file containing Hello World.  I also created the file using vi.
=> Add my helper text file

trainees/hello_090.txt
Please accept my request to add this file. THANK YOU.
=> Adding number file 090 to repo

trainees/hello_093.txt
=> Marty's training contribution

trainees/hello_091.txt
=> My second pr

trainees/hello_119.txt
=> James added

trainees/hello_118.txt
=> hello_118 commit msg

trainees/hello_120.txt
=> this is awesome by Nasif

trainees/hello_121.txt
=> rebaseAnand squashed

trainees/hello_130.txt
=> Added my hello.

trainees/hello_129.txt
=> new file 129

trainees/hello_125.txt
=> miranda's hello file

trainees/hello_127.txt
Please review and merge to master.
=> created hello_127.txt

trainees/hello_134.txt
=> my first request

trainees/hello_132.txt
=> adding my file

trainees/hello_131.txt
my first PR to the spacetelescope/training-ground
=> hello_131 file added

trainees/hello_148.txt
=> my hello file

trainees/hello_145.txt
Nat Kerman added hello_145.txt which just says Hello world!
=> Nat: add hello_145.txt

trainees/hello_142.txt
Please add my file, hello_142.txt
=> James' file

trainees/hello_157.txt
Would you kindly approve this PR for training purposes?
=> Added trainee file

trainees/hello_159.txt
=> added new hello world 159

trainees/hello_168.txt
Completing merge request as part of git training.
=> Added text file 168

trainees/hello_183.txt
=> Add hello_183.txt
